spring:
  application:
    name: AppTour STAG
  config:
    activate:
      on-profile: staging
server:
  port: 8080

---
spring:
  application:
    name: AppTour PROD
  config:
    activate:
      on-profile: production
server:
  port: 8090
---
app:
  user-type:
    admin: ADMIN
    guest: GUEST
    premium: PREMIUM
#logging:
#  pattern:
#    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
